- name: install necessary packages for wireguard
  apt:
    pkg: 
    - wireguard
    # - iptables-persistent
    # - unbound
    # - unbound-host
    # - resolvconf
    state: present
    update_cache: true
  tags:
  - install

- name: stop wireguard
  systemd:
    daemon_reload: true
    state: stopped
    name: wg-quick@wg0
    enabled: true
  ignore_errors: true
  tags:
  - install

- name: template server file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
  tags: 
  - install

- name: template client file
  template:
    src: wg0-client.conf.j2
    dest: "~/Desktop/{{ item.config_name }}"
  delegate_to: localhost
  loop: "{{ clients }}"
  tags: 
  - install

- name: start wireguard
  systemd:
    daemon_reload: true
    state: started
    name: wg-quick@wg0
    enabled: true
    no_block: true
  tags:
  - install

# - name: Make sure netfilter-persistent is enabled
#   systemd:
#     daemon_reload: true
#     state: restarted
#     name: netfilter-persistent
#     enabled: true
#   tags:
#   - install

- name: set ip forwarding
  shell: echo "net.ipv4.ip_forward=1" > /etc/sysctl.conf && sysctl -p
  tags:
  - install